[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Next.js App Router support với static export
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 