[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Next.js App Router support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 